use mes_trace;
TRUNCATE TABLE bc_label_rule;
TRUNCATE TABLE bc_label_rule_detail;
TRUNCATE TABLE bom_header;
TRUNCATE TABLE bom_line;
TRUNCATE TABLE bom_routing_detail;
TRUNCATE TABLE bom_routing_header;
TRUNCATE TABLE bom_routing_line;
TRUNCATE TABLE bom_standard_operation;
TRUNCATE TABLE item;
TRUNCATE TABLE locator;
TRUNCATE TABLE pallet_specification;
TRUNCATE TABLE subinventory;
